export const AUTH_START = 'AUTH_START';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FETCH_PROJECTS_START = 'FETCH_USER_PROJECTS_START';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';
export const FETCH_PROJECTS_FAIL = 'FETCH_PROJECTS_FAIL';

export const FETCH_ISSUES_START = 'FETCH_ISSUES_START';
export const FETCH_ISSUES_SUCCESS = 'FETCH_ISSUES_SUCCESS';
export const FETCH_ISSUES_FAIL = 'FETCH_ISSUES_FAIL';

export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';

export const FETCH_PROJECT_ISSUES_START = 'FETCH_PROJECT_ISSUES_START';
export const FETCH_PROJECT_ISSUES_SUCCESS = 'FETCH_PROJECT_ISSUES_SUCCESS';
export const FETCH_PROJECT_ISSUES_FAIL = 'FETCH_PROJECT_ISSUES_FAIL';

export const FETCH_PROJECT_START = 'FETCH_PROJECT_START';
export const FETCH_PROJECT_SUCCESS = 'FETCH_PROJECT_SUCCESS';
export const FETCH_PROJECT_FAIL = 'FETCH_PROJECT_FAIL';

export const FETCH_USER_START = 'FETCH_USER_START';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';

export const FETCH_USER_PROJECTS_START = 'FETCH_USER_PROJECTS_START';
export const FETCH_USER_PROJECTS_SUCCESS = 'FETCH_USER_PROJECTS_SUCCESS';
export const FETCH_USER_PROJECTS_FAIL = 'FETCH_USER_PROJECTS_FAIL';

export const FETCH_USER_ISSUES_REPORTED_START = 'FETCH_USER_ISSUES_REPORTED_START';
export const FETCH_USER_ISSUES_REPORTED_SUCCESS = 'FETCH_USER_ISSUES_REPORTED_SUCCESS';
export const FETCH_USER_ISSUES_REPORTED_FAIL = 'FETCH_USER_ISSUES_REPORTED_FAIL';

export const FETCH_USER_ISSUES_ASSIGNED_START = 'FETCH_USER_ISSUES_ASSIGNED_START';
export const FETCH_USER_ISSUES_ASSIGNED_SUCCESS = 'FETCH_USER_ISSUES_ASSIGNED_SUCCESS';
export const FETCH_USER_ISSUES_ASSIGNED_FAIL = 'FETCH_USER_ISSUES_ASSIGNED_FAIL';
