export const AUTH_START = 'AUTH_START';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FETCH_PROJECTS_START = 'FETCH_PROJECTS_START';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';
export const FETCH_PROJECTS_FAIL = 'FETCH_PROJECTS_FAIL';

export const FETCH_ISSUES_START = 'FETCH_ISSUES_START';
export const FETCH_ISSUES_SUCCESS = 'FETCH_ISSUES_SUCCESS';
export const FETCH_ISSUES_FAIL = 'FETCH_ISSUES_FAIL';

export const FETCH_PROJECT_ISSUES_START = 'FETCH_PROJECT_ISSUES_START';
export const FETCH_PROJECT_ISSUES_SUCCESS = 'FETCH_PROJECT_ISSUES_SUCCESS';
export const FETCH_PROJECT_ISSUES_FAIL = 'FETCH_PROJECT_ISSUES_FAIL';
