# Generated by Django 4.0 on 2022-01-22 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugphile_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='url',
            new_name='link',
        ),
    ]
