# Generated by Django 4.0 on 2022-01-22 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugphile_app', '0002_rename_url_project_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuepriority',
            options={'verbose_name': 'Issue Priority', 'verbose_name_plural': 'Issue Priorities'},
        ),
    ]
