# Generated by Django 4.0 on 2022-01-22 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugphile_app', '0003_alter_issuepriority_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuestatus',
            options={'verbose_name': 'Issue Status', 'verbose_name_plural': 'Issue Statuses'},
        ),
        migrations.AlterModelOptions(
            name='projectstatus',
            options={'verbose_name': 'Project Status', 'verbose_name_plural': 'Project Statuses'},
        ),
    ]
